package com.bawei.lqy.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.lqy.model.dao.LeftGsonBean;
import com.bawei.lqy.model.dao.RightGsonBean;

import com.bawei.lqy.database.LeftGsonBeanDao;
import com.bawei.lqy.database.RightGsonBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig leftGsonBeanDaoConfig;
    private final DaoConfig rightGsonBeanDaoConfig;

    private final LeftGsonBeanDao leftGsonBeanDao;
    private final RightGsonBeanDao rightGsonBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        leftGsonBeanDaoConfig = daoConfigMap.get(LeftGsonBeanDao.class).clone();
        leftGsonBeanDaoConfig.initIdentityScope(type);

        rightGsonBeanDaoConfig = daoConfigMap.get(RightGsonBeanDao.class).clone();
        rightGsonBeanDaoConfig.initIdentityScope(type);

        leftGsonBeanDao = new LeftGsonBeanDao(leftGsonBeanDaoConfig, this);
        rightGsonBeanDao = new RightGsonBeanDao(rightGsonBeanDaoConfig, this);

        registerDao(LeftGsonBean.class, leftGsonBeanDao);
        registerDao(RightGsonBean.class, rightGsonBeanDao);
    }
    
    public void clear() {
        leftGsonBeanDaoConfig.clearIdentityScope();
        rightGsonBeanDaoConfig.clearIdentityScope();
    }

    public LeftGsonBeanDao getLeftGsonBeanDao() {
        return leftGsonBeanDao;
    }

    public RightGsonBeanDao getRightGsonBeanDao() {
        return rightGsonBeanDao;
    }

}
