package com.bawei.lqy.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.lqy.model.dao.LeftGsonBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "LEFT_GSON_BEAN".
*/
public class LeftGsonBeanDao extends AbstractDao<LeftGsonBean, Void> {

    public static final String TABLENAME = "LEFT_GSON_BEAN";

    /**
     * Properties of entity LeftGsonBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property GetJson = new Property(0, String.class, "getJson", false, "GET_JSON");
    }


    public LeftGsonBeanDao(DaoConfig config) {
        super(config);
    }
    
    public LeftGsonBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"LEFT_GSON_BEAN\" (" + //
                "\"GET_JSON\" TEXT);"); // 0: getJson
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"LEFT_GSON_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, LeftGsonBean entity) {
        stmt.clearBindings();
 
        String getJson = entity.getGetJson();
        if (getJson != null) {
            stmt.bindString(1, getJson);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, LeftGsonBean entity) {
        stmt.clearBindings();
 
        String getJson = entity.getGetJson();
        if (getJson != null) {
            stmt.bindString(1, getJson);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public LeftGsonBean readEntity(Cursor cursor, int offset) {
        LeftGsonBean entity = new LeftGsonBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // getJson
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, LeftGsonBean entity, int offset) {
        entity.setGetJson(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(LeftGsonBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(LeftGsonBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(LeftGsonBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
