package com.bawei.lqy.database;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.bawei.lqy.model.dao.RightGsonBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RIGHT_GSON_BEAN".
*/
public class RightGsonBeanDao extends AbstractDao<RightGsonBean, Void> {

    public static final String TABLENAME = "RIGHT_GSON_BEAN";

    /**
     * Properties of entity RightGsonBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property GetJson = new Property(0, String.class, "getJson", false, "GET_JSON");
    }


    public RightGsonBeanDao(DaoConfig config) {
        super(config);
    }
    
    public RightGsonBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RIGHT_GSON_BEAN\" (" + //
                "\"GET_JSON\" TEXT);"); // 0: getJson
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RIGHT_GSON_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RightGsonBean entity) {
        stmt.clearBindings();
 
        String getJson = entity.getGetJson();
        if (getJson != null) {
            stmt.bindString(1, getJson);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RightGsonBean entity) {
        stmt.clearBindings();
 
        String getJson = entity.getGetJson();
        if (getJson != null) {
            stmt.bindString(1, getJson);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public RightGsonBean readEntity(Cursor cursor, int offset) {
        RightGsonBean entity = new RightGsonBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // getJson
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RightGsonBean entity, int offset) {
        entity.setGetJson(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(RightGsonBean entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(RightGsonBean entity) {
        return null;
    }

    @Override
    public boolean hasKey(RightGsonBean entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
